apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ecommerce"},"name":"ecommerce-service","namespace":"ecommerce-bluegreen"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000}],"selector":{"app":"ecommerce","version":"blue"},"type":"ClusterIP"}}
  creationTimestamp: "2026-06-09T12:03:38Z"
  labels:
    app: ecommerce
  name: ecommerce-service
  namespace: ecommerce-bluegreen
  resourceVersion: "56897"
  uid: c7e8f35d-acea-4c68-9188-4328073e9edc
spec:
  clusterIP: 10.0.128.33
  clusterIPs:
  - 10.0.128.33
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecommerce
    version: green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
