apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ecommerce"},"name":"ecommerce-service","namespace":"ecommerce-bluegreen"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000}],"selector":{"app":"ecommerce","version":"blue"},"type":"ClusterIP"}}
  creationTimestamp: "2026-06-09T00:42:55Z"
  labels:
    app: ecommerce
  name: ecommerce-service
  namespace: ecommerce-bluegreen
  resourceVersion: "2151"
  uid: a393c6ee-8d8e-46c3-89d9-2a9cfc5b70ce
spec:
  clusterIP: 10.0.52.180
  clusterIPs:
  - 10.0.52.180
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecommerce
    version: blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
