apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ecommerce"},"name":"ecommerce-service","namespace":"ecommerce-bluegreen"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000}],"selector":{"app":"ecommerce","version":"blue"},"type":"ClusterIP"}}
  creationTimestamp: "2026-06-08T16:49:25Z"
  labels:
    app: ecommerce
  name: ecommerce-service
  namespace: ecommerce-bluegreen
  resourceVersion: "390157"
  uid: 19ff49db-4037-4d41-b79f-f555ff49ffed
spec:
  clusterIP: 10.96.165.65
  clusterIPs:
  - 10.96.165.65
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecommerce
    version: blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
