apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ecommerce"},"name":"ecommerce-service","namespace":"ecommerce-bluegreen"},"spec":{"ports":[{"name":"http","port":80,"targetPort":3000}],"selector":{"app":"ecommerce","version":"blue"},"type":"ClusterIP"}}
  creationTimestamp: "2026-06-08T21:21:27Z"
  labels:
    app: ecommerce
  name: ecommerce-service
  namespace: ecommerce-bluegreen
  resourceVersion: "22525"
  uid: 21915eee-b4a4-47fb-99c0-dbfb7fd922b4
spec:
  clusterIP: 10.0.49.164
  clusterIPs:
  - 10.0.49.164
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecommerce
    version: green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
